### ISSUE TITLE
itsabinashb - LiquidationModule.sol::_accountFundingFees(): function call occured with wrong argument

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-12-flatmoney-judging#10]
itsabinashb

high

# LiquidationModule.sol::_accountFundingFees(): function call occured with wrong argument

## Summary
In `_accountFundingFees()` of `LiquidationModule.sol` contract there is a external call to `PerpMath.sol::_currentFundingRate()`, mistakenly wrong argument was passed to `_currentFundingRate()`.

## Vulnerability Detail
The external call which I am talking about in `_accountFundingFees()` looks like this:
```solidity
    
        int256 currentFundingRate = PerpMath._currentFundingRate({
            proportionalSkew: PerpMath._proportionalSkew({
                skew: currMarketSkew,
                stableCollateralTotal: stableCollateralTotal
            }),
            lastRecomputedFundingRate: vault.lastRecomputedFundingRate(),
            lastRecomputedFundingTimestamp: vault.lastRecomputedFundingTimestamp(),
            maxFundingVelocity: vault.maxFundingVelocity(),
            maxVelocitySkew: vault.maxVelocitySkew()
        });
```
Here we can see this call passing `proportionalSkew` as first argument. But if we see the `_currentFundingRate()`:
```solidity
    function _currentFundingRate(
        int256 lastRecomputedFundingRate,
        uint64 lastRecomputedFundingTimestamp,
        int256 proportionalSkew,
        uint256 maxFundingVelocity,
        uint256 maxVelocitySkew
    ) internal view returns (int256 currFundingRate) {
        return
            lastRecomputedFundingRate +
            _fundingChangeSinceRecomputed(
                proportionalSkew,
                lastRecomputedFundingTimestamp,
                maxFundingVelocity,
                maxVelocitySkew
            );
    }
```
We can see that first argument it is taking `lastRecomputedFundingRate`, and `proportionalSkew` should be 3rd argument, but when this function was called from `LiquidationModule` it is passing `lastRecomputedFundingTimestamp` as 3rd argument. So it is clear to understand that in `PerpMath` library `proportionalSkew` is considered as `lastRecomputedFundingRate` and `lastRecomputedFundingTimestamp` is considered as `proportionalSkew`.

## Impact
As arguments were flipped the `_currentFundingRate()` will return wrong value we will get wrong funding fees.

## Code Snippet
1. https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/libraries/PerpMath.sol#L66-L81
2. https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/LiquidationModule.sol#L338-L347

## Tool used

Manual Review

## Recommendation
Pass those arguments in correct order.

**Comment by nevillehuang** [comment]
Invalid, I don't believe the ordering matters when `proportionalSkew` is explicitly denoted in a `{}` braces
