### ISSUE TITLE
poslednaya - Incorrect calculation of `pnl` lead to wrong `GlobalPositionData`. Division by `0`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-flatmoney-judging#121]
poslednaya

medium

# Incorrect calculation of `pnl` lead to wrong `GlobalPositionData`. Division by `0`

## Summary

Incorrect calculation of `pnl` lead to wrong `GlobalPositionData`. Division by `0`.

## Vulnerability Detail

In `PerpMath` contract `_profiLossTotal` function calculate `pnl` with division by `price` at the end. What is the purpose of this operation?

Also if `price` will be `0` we will get division by `0`. 

Example of calculation:

```solidity
// price = 1000;
// globalPosition.lastPrice = 900
// globalPosition.sizeOpenedTotal 12345

int256 priceShift = int256(price) - int256(globalPosition.lastPrice);
// 1000 - 900 == 100

return (int256(globalPosition.sizeOpenedTotal) * (priceShift)) / int256(price);
// 12345 * 100 = 1234500 -> / 1000 == 1234.5
```

## Impact

Incorrect calculation of GlobalPosition and another calculations based on `PerpMath::_profitLoss()` and `PerpMath::_profitLossTotal()`. Division by `0` if `price` == `0`.  

## Code Snippet

PerpMath.sol (192-199)

```solidity
    function _profitLossTotal(
        FlatcoinStructs.GlobalPositions memory globalPosition,
        uint256 price
    ) internal pure returns (int256 pnl) {
        int256 priceShift = int256(price) - int256(globalPosition.lastPrice);

        return (int256(globalPosition.sizeOpenedTotal) * (priceShift)) / int256(price);
    }
```

\
PerpMath.sol (175-184)

```solidity
    function _profitLoss(FlatcoinStructs.Position memory position, uint256 price) internal pure returns (int256 pnl) {
        int256 priceShift = int256(price) - int256(position.lastPrice);
        int256 profitLossTimesTen = (int256(position.additionalSize) * (priceShift) * 10) / int256(price);

        if (profitLossTimesTen % 10 != 0) {
            return profitLossTimesTen / 10 - 1;
        } else {
            return profitLossTimesTen / 10;
        }
    }
```

## Tool used

Manual Review

## Recommendation

Consider the calculation of "clean" `pnl` and implement another conversions in other functions. 

This is how Synthetix implemented it: 

https://github.com/Synthetixio/synthetix/blob/cbd8666f4331ee95fcc667ec7345d13c8ba77efb/contracts/PerpsV2MarketBase.sol#L156%3E///%20%20%20%20%20%20and%20%3Chttps://github.com/Synthetixio/synthetix/blob/cbd8666f4331ee95fcc667ec7345d13c8ba77efb/contracts/SafeDecimalMath.sol%3E

```solidity
    function _profitLoss(Position memory position, uint price) internal pure returns (int pnl) {
        int priceShift = int(price).sub(int(position.lastPrice));
        return int(position.size).multiplyDecimal(priceShift);
    }
```

**Comment by nevillehuang** [comment]
Invalid, price cannot be 0 based on this check [here](https://github.com/sherlock-audit/2023-12-flatmoney/blob/bba4f077a64f43fbd565f8983388d0e985cb85db/flatcoin-v1/src/OracleModule.sol#L153-L156)
