### ISSUE TITLE
krkba - Age can be manipulated in  `setExecutabilityAge` function.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-flatmoney-judging#13]
krkba

high

# Age can be manipulated in  `setExecutabilityAge` function.

krkba
## Summary
There is lack of validation in `setExecutabilityAge` function.
## Vulnerability Detail
The `_minExecutabilityAge` can be greater than `_maxExecutabilityAge` because there is no check if `_minExecutabilityAge` is less than `_maxExecutabilityAge` or not.
as example : 
we can set `_minExecutabilityAge` to 10
and we can set `_maxExecutabilityAge` to 7 without any restriction.
## Impact
It can lead to function or the whole contract manipulation.
## Code Snippet
https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/FlatcoinVault.sol#L417-L423
## Tool used

Manual Review

## Recommendation
Add check to ensure that `_minExecutabilityAge` is not greater then `_maxExecutabilityAge` .

**Comment by nevillehuang** [comment]
Invalid, admin only function, they are trusted to set appropriate executability age parameters
