### ISSUE TITLE
Dliteofficial - `_maxAge()` might cause transactions to revert due to staleness check in `OracleModule`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-flatmoney-judging#147]
Dliteofficial

medium

# `_maxAge()` might cause transactions to revert due to staleness check in `OracleModule`

## Summary
A low maxAge value might cause transactions in `StableModule` and `LeverageModule` to revert for the failure to meet the staleness check in `OracleModule::_getPrice()`

## Vulnerability Detail
During the execution of an announced deposit order in [`StableModule::executeDeposit()`](https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/StableModule.sol#L61C5-L88C1), the function checks the time passed since executionAtTime. The result of this call, maxAge, is used in the staleness check in [`OracleModule::_getPrice()`](https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/OracleModule.sol#L106C5-L128C10). The issue here is that when maxAge is less than `onchainOracle.maxAge` and `offchainOracle.maxAge`, the staleness check in `_getOnchainPrice()` and `_getOffchainPrice()` will pass but the one in `OracleModule::_getPrice()` (see code snippet) will fail. The same applies to the others in `StableModule` and `LeverageModule`

## Impact
executeOrder transactions will fail on execution due to the failure of maxAge to meet the staleness check

## Code Snippet
`StableModule::executeDeposit()`
```solidity
    function executeDeposit(
        address _account,
        uint64 _executableAtTime,
        FlatcoinStructs.AnnouncedStableDeposit calldata _announcedDeposit
    ) external whenNotPaused onlyAuthorizedModule returns (uint256 _liquidityMinted) {
        uint256 depositAmount = _announcedDeposit.depositAmount;

        uint32 maxAge = _getMaxAge(_executableAtTime);

        _liquidityMinted = (depositAmount * (10 ** decimals())) / stableCollateralPerShare(maxAge);

        if (_liquidityMinted < _announcedDeposit.minAmountOut)
            revert FlatcoinErrors.HighSlippage(_liquidityMinted, _announcedDeposit.minAmountOut);

        _mint(_account, _liquidityMinted);

        vault.updateStableCollateralTotal(int256(depositAmount));

        if (totalSupply() < MIN_LIQUIDITY)
            revert FlatcoinErrors.AmountTooSmall({amount: totalSupply(), minAmount: MIN_LIQUIDITY});

        IPointsModule pointsModule = IPointsModule(vault.moduleAddress(FlatcoinModuleKeys._POINTS_MODULE_KEY));
        pointsModule.mintDeposit(_account, _announcedDeposit.depositAmount);

        emit FlatcoinEvents.Deposit(_account, depositAmount, _liquidityMinted);
    }
```
`OracleModule::_getPrice()`
```solidity
    function _getPrice(uint32 maxAge) internal view returns (uint256 price, uint256 timestamp) {

        ...

        if (maxAge < type(uint32).max && timestamp + maxAge < block.timestamp) {
            revert FlatcoinErrors.PriceStale(
                offchain ? FlatcoinErrors.PriceSource.OffChain : FlatcoinErrors.PriceSource.OnChain
            );
        }
    }
```

## Tool used

Manual Review

## Recommendation
Consider removing `_getMaxAge()`

`StableModule::executeDeposit()`
```diff
    function executeDeposit(
        address _account,
        uint64 _executableAtTime,
        FlatcoinStructs.AnnouncedStableDeposit calldata _announcedDeposit
    ) external whenNotPaused onlyAuthorizedModule returns (uint256 _liquidityMinted) {
        uint256 depositAmount = _announcedDeposit.depositAmount;

-        uint32 maxAge = _getMaxAge(_executableAtTime);
        _liquidityMinted = (depositAmount * (10 ** decimals())) / stableCollateralPerShare(maxAge);

        if (_liquidityMinted < _announcedDeposit.minAmountOut)
            revert FlatcoinErrors.HighSlippage(_liquidityMinted, _announcedDeposit.minAmountOut);

        _mint(_account, _liquidityMinted);

        vault.updateStableCollateralTotal(int256(depositAmount));

        if (totalSupply() < MIN_LIQUIDITY)
            revert FlatcoinErrors.AmountTooSmall({amount: totalSupply(), minAmount: MIN_LIQUIDITY});

        IPointsModule pointsModule = IPointsModule(vault.moduleAddress(FlatcoinModuleKeys._POINTS_MODULE_KEY));
        pointsModule.mintDeposit(_account, _announcedDeposit.depositAmount);

        emit FlatcoinEvents.Deposit(_account, depositAmount, _liquidityMinted);
    }
```

Duplicate of #170

**Comment by securitygrid** [comment]
Escalate
This isssue is not dup of #170 due to insufficient proof.

**Comment by sherlock-admin2** [comment]
> Escalate
> This isssue is not dup of #170 due to insufficient proof.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Planning to reject and keep issue state as is. I believe it's clear that the report is describing the same core issue as described in #170

**Comment by nevillehuang** [comment]
Agree with @Evert0x

**Comment by Czar102** [comment]
Result:
Medium
Duplicate of #170

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [securitygrid](https://github.com/sherlock-audit/2023-12-flatmoney-judging/issues/147/#issuecomment-1956235836): rejected
