### ISSUE TITLE
krkba - `marginDepositedTotal` can be negative.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-flatmoney-judging#15]
krkba

high

# `marginDepositedTotal` can be negative.

kekba
## Vulnerability Detail
In the `settleFundingFees` function, there is a check to ensure that the `marginDepositedTotal` is not negative after applying the funding fees. However,this could potentially lead to a negative `marginDepositedTotal` if the funding fees are too high.
## Impact
Negative `marginDepositedTotal`
## Code Snippet
https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/FlatcoinVault.sol#L216-L237
## Tool used

Manual Review

## Recommendation
Add a check before applying the funding fees to ensure that the `marginDepositedTotal` is not negative.

**Comment by nevillehuang** [comment]
Invalid, seemingly duplicate of #181, but lacks sufficient impact description and proof
