### ISSUE TITLE
krkba - Incorrect calculation of the `currentFundingRate_` value.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-flatmoney-judging#19]
krkba

medium

# Incorrect calculation of the `currentFundingRate_` value.

krkba
## Vulnerability Detail
In the `getCurrentFundingRate` function, the `currentFundingRate_` return value is calculated using the `PerpMath._currentFundingRate` function, which takes several arguments as input. However, there is no check to ensure that the input arguments are valid.
## Impact
Incorrect calculation of the `currentFundingRate_` value.
## Code Snippet
https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/FlatcoinVault.sol#L261-L273
## Tool used

Manual Review

## Recommendation
Add checks for each input argument to ensure that they are valid. example:
```solidity
if (proportionalSkew < 0) revert FlatcoinErrors.InvalidProportionalSkew(proportionalSkew);
if (lastRecomputedFundingRate > 0 && lastRecomputedFundingRate < -1e18)
    revert FlatcoinErrors.InvalidLastRecomputedFundingRate(lastRecomputedFundingRate);
if (lastRecomputedFundingTimestamp == 0) revert FlatcoinErrors.ZeroValue("lastRecomputedFundingTimestamp");
if (maxFundingVelocity <= 0) revert FlatcoinErrors.InvalidMaxFundingVelocity(maxFundingVelocity);
if (maxVelocitySkew <= 0 || maxVelocitySkew > 1e18)
    revert FlatcoinErrors.InvalidMaxVelocitySkew(maxVelocitySkew);
```

**Comment by nevillehuang** [comment]
Invalid, no impact shown to finding. Additionally, this is a view function not used anywhere else in the protocol, so would be invalid based on sherlock [rules](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid)

> 16. Incorrect values in View functions are by default considered low.
