### ISSUE TITLE
shaka - `StableModule.executeWithdraw` reverts when the stable collateral per share is lower than 1e6

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-flatmoney-judging#221]
shaka

medium

# `StableModule.executeWithdraw` reverts when the stable collateral per share is lower than 1e6

## Summary

`StableModule.executeWithdraw` reverts when the stable collateral per share is lower than 1e6.

## Vulnerability Detail

`StableModule.executeWithdraw` [has a check](https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/StableModule.sol#L121-L124) to prevent significant impact on stable token price during withdrawal.

The problem is that when the stable collateral per share is lower than 1e6, the check will provoke a revert due to an underflow error.

## Impact

Stable token holder will not be able to withdraw their funds when the stable collateral per share is lower than 1e6.

## Code Snippet

https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/StableModule.sol#L122

## Tool used

Manual Review

## Recommendation

```diff
File: StableModule.sol

        if (totalSupply() > 0) {
            if (
                stableCollateralPerShareAfter < stableCollateralPerShareBefore - 1e6 ||
+               (stableCollateralPerShareBefore >= 1e6 && stableCollateralPerShareAfter < stableCollateralPerShareBefore - 1e6) ||
                stableCollateralPerShareAfter > stableCollateralPerShareBefore + 1e6
            ) revert FlatcoinErrors.PriceImpactDuringWithdraw();
```

**Comment by nevillehuang** [comment]
Invalid, `stableCollateralPerShare` will have a minimum value of 1e18 as seen [here](https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/StableModule.sol#L217)
