### ISSUE TITLE
krkba - Unprotected Functions ` _lock` and `_unlock`.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-flatmoney-judging#25]
krkba

medium

# Unprotected Functions ` _lock` and `_unlock`.

krkba
## Summary
Unprotected Functions.
## Vulnerability Detail
`_lock` and `_unlock` functions are internal and can be called by any function within the contract or any derived contracts.
## Impact
Unauthorized locking or unlocking of tokens.
## Code Snippet
https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/misc/ERC20LockableUpgradeable.sol#L27-L43
## Tool used

Manual Review

## Recommendation
Add access control to these functions.

**Comment by nevillehuang** [comment]
Invalid, `_lock()` and `_unlock()` are internal functions, they cannot be called externally
