### ISSUE TITLE
rekxor - PointsModule.sol :: _mintTo() function doesn't follow CEI pattern.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-flatmoney-judging#255]
rekxor

medium

# PointsModule.sol :: _mintTo() function doesn't follow CEI pattern.

## Summary
The function `_mintTo()` doesn't follow the Check Effects Interactions pattern.

## Vulnerability Detail
The function `_mintTo()` doesn't follow the Check Effects Interactions pattern, it makes call to the `_mint()` function before applying effects on the amount via `_lock()` and `_setMintUnlockTime()`

## Impact
Though the _mint() call is to ERC20Upgradeable contract, but it is still not a good practice to code without incorporating the CEI pattern in the smart contracts.

## Code Snippet
[Code Location](https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/PointsModule.sol#L169)

```javascript
function _mintTo(address to, uint256 amount) internal {
        if (amount < 1e6) {
            // avoids potential precision errors on unlock time calculations
            revert FlatcoinErrors.MintAmountTooLow(amount);
        }

        uint256 _unlockTime = unlockTime[to];

        if (_unlockTime > 0 && _unlockTime <= block.timestamp) {
            // lock has expired, so unlock existing tokens first
            _unlock(to, _lockedAmount[to]);
        }
        //@audit _lock, _setMintUnlockTime needs to be updated first then do _mint 
        _mint(to, amount);
        _lock(to, amount);
        _setMintUnlockTime(to, amount);
    }
```

## Tool used

Manual Review

## Recommendation
Keep the order of function calls as follows to follow the best practices:
```solidity
        _lock(to, amount);
        _setMintUnlockTime(to, amount);
        _mint(to, amount);
```

**Comment by nevillehuang** [comment]
Invalid, insufficient proof to show reentrancy is possible required by sherlock rules. Additionally, you cannot reenter an ERC20 internal `_mint()` function
