### ISSUE TITLE
Afriauditor - make if (quotedAmount < minAmountOut) in delayedorder:announceStableDeposit (quotedAmount <= minAmountOut)

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-flatmoney-judging#289]
Afriauditor

medium

# make if (quotedAmount < minAmountOut) in delayedorder:announceStableDeposit (quotedAmount <= minAmountOut)

## Summary
make if (quotedAmount < minAmountOut) in delayedorder:announceStableDeposit (quotedAmount <= minAmountOut)

## Vulnerability Detail
this will enable trade execute when price is also exactly at slippage

## Impact
Enable trade execution at exactly slippage

## Code Snippet
https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/DelayedOrder.sol#L83

## Tool used

Manual Review

## Recommendation
change < to <=

**Comment by nevillehuang** [comment]
Invalid, slippage working as intended, the if quotedAmount == minAmountOut, it should not revert.
