### ISSUE TITLE
Anubis - Inadequate Keeper Fee and Slippage Validation

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-flatmoney-judging#29]
Anubis

medium

# Inadequate Keeper Fee and Slippage Validation

## Summary
The **DelayedOrder** contract's management of keeper fees and control of minimum slippage in order announcement functions could lead to financial inefficiencies and potential losses.
## Vulnerability Detail
Suppose a user announces a stable deposit with **depositAmount = 1,000** tokens, a **minAmountOut = 900** tokens, and a **keeperFee = 100** tokens. The contract directly transfers **depositAmount + keeperFee = 1,100** tokens without validating if the keeper fee is excessive or misaligned with market conditions. Additionally, if the **quotedAmount** received for the **depositAmount** is significantly less than **minAmountOut** (e.g., only 850 tokens due to market volatility), the user might still proceed with the transaction, facing an undesired high slippage.

```solidity
function announceStableDeposit(
    uint256 depositAmount,
    uint256 minAmountOut,
    uint256 keeperFee
) external whenNotPaused {
    // ...
    vault.collateral().safeTransferFrom(msg.sender, address(this), depositAmount + keeperFee);
    // ...
}
```

## Impact
This issue could result in users paying excessive fees for keeper services or facing high slippage without adequate warning, leading to financial losses.
## Code Snippet
https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/DelayedOrder.sol#L67-L102
## Tool used

Manual Review

## Recommendation
**1. Dynamic Keeper Fee Calculation:**
Implement a method to calculate keeper fees dynamically, ensuring they align with transaction complexity and market conditions.

**2. Enhanced Slippage Checks:**
Introduce stricter checks on the minAmountOut parameter to safeguard against high slippage scenarios.

// Dynamic Fee Calculation
function calculateDynamicKeeperFee(uint256 transactionAmount) internal view returns (uint256) {
    // Logic for calculating dynamic fees
}

```solidity
// Enhanced Slippage Checks
function validateSlippage(uint256 quotedAmount, uint256 minAmountOut) internal pure {
    require(quotedAmount >= minAmountOut, "Slippage exceeds tolerance");
}

// Implementing in announce functions
function announceStableDeposit(uint256 depositAmount, uint256 minAmountOut, uint256 keeperFee) external whenNotPaused {
    uint256 calculatedFee = calculateDynamicKeeperFee(depositAmount);
    require(keeperFee >= calculatedFee && keeperFee <= maxFeeLimit, "Invalid keeper fee");
    validateSlippage(quotedAmount, minAmountOut);
    // Continue with the rest of the function...
}
```

**Comment by nevillehuang** [comment]
Invalid, slippage check is correct, keeperFee is user inputted, they are responsible to adhere to current keeper fees to update necessary prices and execute orders accordingly. Fees checks are done by out-of-scope pyth oracle seen [here](https://goerli.basescan.org/address/0xf5bbe9558f4bf37f1eb82fb2cedb1c775fa56832#code%23F24%23L75)
