### ISSUE TITLE
E1 - Users who want to liquidate can be frontrun

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-flatmoney-judging#35]
E1

medium

# Users who want to liquidate can be frontrun

## Summary
All profitable for liquidation positions can be frontrun by MEV bots. 

## Vulnerability Detail
Both liquidation functions, allow users to call them and liquidate positions which pass the liquidation criteria, however in reality all profitable positions will be frontrun by bots leading the users to only lose gases calling them, hence lose trust in the project. 

## Impact
Users who want to earn extra fees by liquidating position will end up losing gas fees and not earning anything.

## Code Snippet
https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/LiquidationModule.sol#L75

https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/LiquidationModule.sol#L85

## Tool used

Manual Review

## Recommendation
Consider only users of the protocol to be able to liquidate

**Comment by nevillehuang** [comment]
Invalid, this is describing how typical liquidation mechanism works. Liquidation should be assigned to the first liquidator that captures the opportunity.
