### ISSUE TITLE
Anubis - Poor Management of Price Slippage in Trade Execution

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-flatmoney-judging#39]
Anubis

high

# Poor Management of Price Slippage in Trade Execution

## Summary
The contract does not effectively manage price slippage during trade execution, leading to potential financial losses or unfair trading conditions.
## Vulnerability Detail
In trading operations, particularly those involving large orders or volatile markets, slippage can significantly impact the execution price. If the **DelayedOrder** contract doesn't adequately account for or limit slippage, users could experience worse-than-expected trade outcomes.

```solidity
// Code from the contract demonstrating the issue
function executeOrder(...) external {
    // ...
    // Issue: No mechanism to check or limit price slippage
    executeTrade(...);
}
```

## Impact
Scenario with Calculations:
User A places a large order, expecting execution at a quoted price of $100.
Due to high market volatility and no slippage control, the order executes at $110.
For a 1000 unit order, this results in an unexpected additional cost of $10,000 (1000 units * $10 extra per unit).
## Code Snippet
https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/DelayedOrder.sol#L378
## Tool used

Manual Review

## Recommendation
**Implement Slippage Control Mechanisms:**
Introduce checks to limit the acceptable slippage range during trade executions, protecting users from excessive price movements.

**Proposed Code Fix:**
```solidity
function executeOrder(...) external {
    // ...
    // Implement slippage control
    require(isSlippageWithinLimit(...), "Excessive slippage");
    executeTrade(...);
}
```
This modification will help ensure that trades are executed within acceptable price ranges, enhancing user trust and fairness in the trading process.

**Comment by nevillehuang** [comment]
Invalid, there are already existing slippage protections in place during announcement of orders before execution
