### ISSUE TITLE
r0ck3tz - The execution of limit order can be front-runned

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-flatmoney-judging#49]
r0ck3tz

medium

# The execution of limit order can be front-runned

## Summary

The execution of a limit order by the keeper can be front-run by the leverage position's owner, allowing manipulation of the values of the limit order.

## Vulnerability Detail

The LimitOrder implements the logic of announcing a limit order via the [`announceLimitOrder`](https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/LimitOrder.sol#L58-L83) function, which later has to be executed through the [`executeLimitOrder`](https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/LimitOrder.sol#L119-L128) function by the keeper. The issue is that the keeper's call to `executeLimitOrder` can be front-run by the leverage position's owner to change the `priceLowerThreshold` and `priceUpperThreshold` values of the limit order via `announceLimitOrder`.

## Impact

The keeper will execute limit order with the `priceLowerThreshold` and `priceUpperThreshold` he did not accept effectively leading to the loss of funds by the keeper.

## Code Snippet
- https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/LimitOrder.sol#L119-L128

## Tool used

Manual Review

## Recommendation

Add a mechanism similar to the slippage protection where `executeLimitOrder` function accepts parameters of `priceLowerThreshold` and `priceUpperThreshold`. In case these values do not match the limit order's values the call should revert.

**Comment by nevillehuang** [comment]
Invalid, front-running is not possible on base, given they use a private mempool see discussions [here](https://github.com/sherlock-audit/2023-12-truflation-judging/issues/124) and comments [here](https://github.com/sherlock-audit/2023-12-truflation-judging/issues/176#issuecomment-1888966579). Additionally, agree with sponsors following comments:

> The point of a limit order is to limit the loss incurred or take the profit as wished by the trader. If they try to frontrun this, it's their loss really.
