### ISSUE TITLE
HSP - Owner may make leverage total skew fraction larger than skewFractionMax unintentionally

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-flatmoney-judging#93]
HSP

medium

# Owner may make leverage total skew fraction larger than skewFractionMax unintentionally

## Summary
Owner may make leverage total skew fraction larger than skewFractionMax unintentionally by updating skewFractionMax.

## Vulnerability Detail
Protocol owner can call [setSkewFractionMax(...)](https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/FlatcoinVault.sol#L339) function to update **skewFractionMax**:
```solidity
    function setSkewFractionMax(uint256 _skewFractionMax) public onlyOwner {
        if (_skewFractionMax < 1e18) revert FlatcoinErrors.InvalidSkewFractionMax(_skewFractionMax);

        skewFractionMax = _skewFractionMax;
    }
```
As we can see from above, **skewFractionMax** is updated a new value directly without a double-check. This can be problematic when owner decrease the value. Consider the following scenario:
1. Owner submits a transaction to lower the **skewFractionMax**, due to network congestion, owner's transaction is not executed immediately;
2. At the same time, a trader announces a leverage adjust to add more size to a position;
3. After the minimum time delay, trader's transaction is executed and position is adjusted, leverage total skew fraction is almost the same as **skewFractionMax**;
4. Owner's transaction gets executed, **skewFractionMax** is updated to a much lower value;
5. Invariant is broken because leverage total skew fraction is higher than **skewFractionMax**.

## Impact
Owner may make leverage total skew fraction larger than skewFractionMax unintentionally.

## Code Snippet
https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/FlatcoinVault.sol#L339-L343

## Tool used
Manual Review

## Recommendation
Add a double-check after **skewFractionMax** is updated to ensure the invariant won't be broken.
```diff
    function setSkewFractionMax(uint256 _skewFractionMax) public onlyOwner {
        if (_skewFractionMax < 1e18) revert FlatcoinErrors.InvalidSkewFractionMax(_skewFractionMax);

        skewFractionMax = _skewFractionMax;

+       checkSkewMax(0);
    }
```

**Comment by nevillehuang** [comment]
Invalid, owners are trusted to supply sufficient gas to make sure transaction execute correctly.

**Comment by 0xhsp** [comment]
Escalate

This issue is valid. 

As descripted in the report, admin may make leverage total skew fraction is higher than **skewFractionMax** unintentionally. Before admin realize this issue and increase skewFractionMax, UNIT holders won't be able to withdraw (to sell collaterals) and may suffer loss due to price fluctuation. 

> Invalid, owners are trusted to supply sufficient gas to make sure transaction execute correctly.

I don't think this is relevant to this issue.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue is valid. 
> 
> As descripted in the report, admin may make leverage total skew fraction is higher than **skewFractionMax** unintentionally. Before admin realize this issue and increase skewFractionMax, UNIT holders won't be able to withdraw (to sell collaterals) and may suffer loss due to price fluctuation. 
> 
> > Invalid, owners are trusted to supply sufficient gas to make sure transaction execute correctly.
> 
> I don't think this is relevant to this issue.
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Planning to reject escalation, the admin is trusted to act in the best interest of the protocol. I also fail to see how this is true. 

> Owner's transaction gets executed, skewFractionMax is updated to a much lower value;

**Comment by nevillehuang** [comment]
Agree with @Evert0x

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xhsp](https://github.com/sherlock-audit/2023-12-flatmoney-judging/issues/93/#issuecomment-1955758575): rejected
