### ISSUE TITLE
cheatcode - Manipulated Prices Distort Critical Funding Rate Adjustments

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-flatmoney-judging#97]
cheatcode

high

# Manipulated Prices Distort Critical Funding Rate Adjustments

## Summary
The settleFundingFees() function in FlatcoinVault relies on getting accurate price data to compute the funding rate and adjustments. However, it presupposes the integrity of the input data without any verification.

If the external price data is artificially manipulated, it can skew the calculations around unrecordedFunding, _fundingFees, and other settlement values that deeply impact the ecosystem's balances and financial stability.

## Vulnerability Detail
```solidity
function settleFundingFees() public returns (int256 _fundingFees) {

  (int256 fundingChangeSinceRecomputed, int256 unrecordedFunding) = _getUnrecordedFunding();

  _fundingFees = PerpMath._accruedFundingTotalByLongs(_globalPositions, unrecordedFunding); 

}
```
## Impact
Inaccurate funding rate adjustments leading to system imbalance

## Code Snippet
https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/FlatcoinVault.sol#L216C5-L237C6

## Tool used
Manual Review

## Recommendation
1. Use decentralized oracle aggregation
2. Implement TWAP smoothing mechanisms
3. Explicitly validate oracle data before settlement calculations

**Comment by nevillehuang** [comment]
Invalid, insufficient proof of finding. There is no input when calling `settleFundingFees()`
