### ISSUE TITLE
cheatcode - Fixed Funding Rate Parameters Vulnerability in FlatcoinVault

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-flatmoney-judging#99]
cheatcode

medium

# Fixed Funding Rate Parameters Vulnerability in FlatcoinVault

## Summary
The FlatcoinVault contract relies on fixed funding rate parameters like maxFundingVelocity and maxVelocitySkew that are crucial for funding rate calculations. These parameters are settable via owner-only functions without additional safeguards. This presents risks of manipulation and inefficiency in volatile market conditions.

## Vulnerability Detail

The setMaxFundingVelocity and setMaxVelocitySkew functions allow the contract owner to update these critical funding rate parameters without any checks or balances. There are no mechanisms to make these parameters adaptive to real-time market conditions like volatility or liquidity. They remain static once set. The lack of dynamic adjustment of these parameters based on market data creates risk of manipulation if oracle input is compromised. The funding rate calculations may not respond properly to fake price data.

In extreme market conditions, fixed funding parameters may not be able to dampen funding rate fluctuations effectively. This can disadvantage stable LPs or leverage traders unfairly.

## Impact
Incorrect funding rate calculations can lead to loss of funds for users and instability of the platform.

## Code Snippet

https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/FlatcoinVault.sol#L348C5-L362C6

```solidity
function setMaxFundingVelocity(uint256 _newMaxFundingVelocity) public onlyOwner {
    settleFundingFees(); // settle funding fees before updating the max funding velocity so that positions are not affected by the change
    maxFundingVelocity = _newMaxFundingVelocity;
}

function setMaxVelocitySkew(uint256 _newMaxVelocitySkew) public onlyOwner {
    if (_newMaxVelocitySkew > 1e18 || _newMaxVelocitySkew == 0)
        revert FlatcoinErrors.InvalidMaxVelocitySkew(_newMaxVelocitySkew);

    settleFundingFees(); // settle funding fees before updating the max velocity skew so that positions are not affected by the change
    maxVelocitySkew = _newMaxVelocitySkew;
}
```

## Tool used
Manual Review

## Recommendation
Incorporate a mechanism that adjusts `maxFundingVelocity` and `maxVelocitySkew` based on real-time market conditions. This could involve algorithms that analyze current market volatility, liquidity, and other relevant metrics to adjust parameters dynamically.

**Comment by nevillehuang** [comment]
Invalid, admin only functions, they are trusted to set and adjust appropriate parameters accordingly based on market conditions. This is simply a suggestion
